version: '3.1'

services:
  vulnapp:
    build:
      context: ./vulnerable-app
    ports:
      - 40000:8080

  ldap:
    build:
      context: ./JNDIExploit
      dockerfile: Dockerfile.build
    command: '--ip ldap --ldapPort 1389 --httpPort 80'
